# Generated by Django 2.0.6 on 2018-11-18 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='estoque_materia_prima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, verbose_name='Identificador')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='materia_prima', verbose_name='Imagem')),
                ('cor', models.CharField(max_length=100, verbose_name='Cor')),
                ('tamanho', models.CharField(max_length=100, verbose_name='Tamanho')),
                ('quantidade', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='estoque_produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, verbose_name='Identificador')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos', verbose_name='Imagem')),
                ('cor', models.CharField(max_length=100, verbose_name='Cor')),
                ('tamanho', models.CharField(max_length=100, verbose_name='Tamanho')),
                ('quantidade', models.BigIntegerField(default=0)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Produto', verbose_name='Produto')),
            ],
        ),
        migrations.CreateModel(
            name='fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Fornecedor')),
                ('slug', models.SlugField(default='forn', max_length=100, verbose_name='Identificador')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo de fornecedor')),
                ('cnpj', models.BigIntegerField(verbose_name='CNPJ')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='E-mail')),
                ('telefone', models.IntegerField(verbose_name='Telefone')),
            ],
        ),
        migrations.AddField(
            model_name='estoque_materia_prima',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.fornecedor'),
        ),
        migrations.AddField(
            model_name='estoque_materia_prima',
            name='materia_prima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Materia', verbose_name='Matéria Prima'),
        ),
    ]
